entity: uczenie-maszynowe-projekt
project: Detection of plant diseases
job: uczenie-maszynowe-projekt/Detection of plant diseases/resnet50:latest
name: resnet50
program: main.py

method: bayes
metric:
  goal: minimize
  name: val_loss
# TODO: add proper parameters for ResNet50
parameters:
  batch_size:
    values:
      - 8
      - 16
      - 32
      - 64
      - 128
  epochs:
    distribution: int_uniform
    max: 100
    min: 20
  learning_rate:
    distribution: uniform
    max: 0.02
    min: 0.005
  n_startup_trials:
    distribution: int_uniform
    max: 10
    min: 0

command:
  - ${env}
  - ${interpreter}
  - ${program}
  - "--model"
  - "resnet50"