entity: uczenie-maszynowe-projekt
project: Detection of plant diseases
job: uczenie-maszynowe-projekt/Detection of plant diseases/mobilenet:latest
name: mobilenet
program: main.py

method: bayes
metric:
  goal: minimize
  name: val_loss
parameters:
  batch_size:
    values:
      - 8
      - 16
      - 32
      - 64
      - 128
  epochs:
    distribution: int_uniform
    max: 100
    min: 20
  learning_rate:
    distribution: uniform
    max: 0.02
    min: 0.0005
  optimizer:
    values:
      - adam
      - sgd

command:
  - python3
  - ${program}
  - "--model"
  - "mobilenet"